baseURL: https://rename-this.github.io/vhs
title: VHS
theme: docsy
enableGitInfo: true
enableRobotsTXT: true
languageCode: en-us

menu:
  main:
  - name: "Documentation"
    url: ""

params:
  github_repo: https://github.com/rename-this/vhs
  github_subdir: site
  github_project_repo: https://github.com/rename-this/vhs
  github_branch: main

  # Enable offline search with Lunr.js
  offlineSearch: true
  offlineSearchSummaryLength: 70
  offlineSearchMaxResults: 10
  
  # Enable mermaid diagrams
  mermaid:
    enable: true
    theme: neutral

  # Adds in the `copy` link on code blocks
  prism_syntax_highlighting: true

  sidebar_search_disable: true

  ui:
    navbar_logo: true
    feedback:
      enable: false
