---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: vhs-webhook-cfg
  namespace: redsky-system
webhooks:
  - clientConfig:
      # This should be updated from
      # kubectl config view --raw --minify --flatten -o jsonpath='{.clusters[].cluster.certificate-authority-data}'
      caBundle:
      service:
        name: vhs-webhook
        namespace: redsky-system
        path: /mutate
    namespaceSelector:
      matchExpressions:
      - key: vhs
        operator: Exists
    failurePolicy: Ignore
    name: vhs.carbon-relay.com
    rules:
      - apiGroups:
          - ""
        apiVersions:
          - v1
        operations:
          - CREATE
        resources:
          - pods

