apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: funsies-gcs
  name: funsies-gcs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: funsies-gcs
  strategy: {}
  template:
    metadata:
      annotations:
        vhs.carbon-relay.com/inject: "true"
        vhs.carbon-relay.com/secret: gcs-creds
        vhs.carbon-relay.com/args: >-
          [
            "--input", "tcp|http",
            "--output", "json|gzip|gcs",
            "--capture-response",
            "--address", "0.0.0.0:80",
            "--prometheus-address", "0.0.0.0:9090",
            "--flow-duration", "30s",
            "--gcs-bucket-name", "vhsdemo",
            "--gcs-object-name", "funsies",
            "--debug"
          ]
      labels:
        app: funsies-gcs
    spec:
      containers:
      - image: nginx:latest
        name: nginx
