apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- https://github.com/redskyops/redskyops-recipes/voting-webapp/application

patchesStrategicMerge:
- |-
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: voting-service
  spec:
    template:
      spec:
        containers:
        - name: voting-service
          resources:
            limits:
              memory: 1500Mi
              cpu: 1000m
            requests:
              memory: 200Mi
              cpu: 100m
        - name: vhs
          image: ghcr.io/rename-this/vhs:edge
          command:
          - /vhs
          args:
          - --input
          - tcp|http
          - --output
          - json|gzip|gcs
          - --capture-response
          - --address
          - 0.0.0.0:80
          - --prometheus-address
          - 0.0.0.0:9090
          - --flow-duration
          - 300s
          - --gcs-bucket-name
          - vhsdemo
          - --debug
          env:
          - name: GOOGLE_APPLICATION_CREDENTIALS
            value: /root/.config/gcloud/service-account.json
          imagePullPolicy: Always
          volumeMounts:
          # GCP
          - mountPath: /root/.config/gcloud
            name: cloud-credentials
        volumes:
        - name: cloud-credentials
          secret:
            secretName: gcs-creds
# Reduce requests/replicas so we can fit this in a small cluster
- |-
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: db
  spec:
    template:
      spec:
        containers:
        - name: db
          resources:
            limits:
              memory: 1500Mi
              cpu: 1000m
            requests:
              memory: 200Mi
              cpu: 100m
- |-
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: redis
  spec:
    template:
      spec:
        containers:
        - name: redis
          resources:
            limits:
              memory: 1500Mi
              cpu: 1000m
            requests:
              memory: 200Mi
              cpu: 100m
- |-
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: result-service
  spec:
    template:
      spec:
        containers:
        - name: result-service
          resources:
            limits:
              memory: 1500Mi
              cpu: 1000m
            requests:
              memory: 200Mi
              cpu: 100m
- |-
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: worker
  spec:
    template:
      spec:
        containers:
        - name: worker
          resources:
            limits:
              memory: 1500Mi
              cpu: 1000m
            requests:
              memory: 200Mi
              cpu: 100m
- |-
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: result-exporter
  spec:
    template:
      spec:
        containers:
        - name: result-exporter
          resources:
            limits:
              memory: 1500Mi
              cpu: 1000m
            requests:
              memory: 200Mi
              cpu: 100m

