apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- https://github.com/redskyops/redskyops-recipes/voting-webapp/application

patchesStrategicMerge:
- |-
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: voting-service
  spec:
    template:
      spec:
        containers:
        - name: vhs
          image: us.gcr.io/carbon-relay-dev/vhs:latest
          command:
          - vhs
          args:
          - --input
          - tcp|http
          - --output
          - jsonbuf|gzip|gcs
          - --capture-response
          - --address
          - 0.0.0.0:80
          - --prometheus-address
          - 0.0.0.0:9090
          - --flow-duration
          - 30s
          - --gcs-bucket-name
          - vhsdemo
          - --gcs-object-name
          - funsies
          - --debug
          imagePullPolicy: IfNotPresent
          volumeMounts:
          # GCP
          - mountPath: /root/.config/gcloud
            name: cloud-credentials
        volumes:
        - name: cloud-credentials
          secret:
            secretName: gcs-creds
