name: main

on:
  push:
    branches:
    - main

jobs:

  container:
    name: container
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Cache Docker layers
      id: cache
      uses: actions/cache@v2.1.4
      with:
        path: |
          /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-

    - name: Login to ghcr.io
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: vcr-bot
        password: ${{ secrets.GHCR_TOKEN }}

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: ./
        file: ./docker/vhs/Dockerfile
        platforms: linux/amd64
        builder: ${{ steps.buildx.outputs.name }}
        push: true
        target: application
        tags: |
          ghcr.io/${{ github.repository }}:${{ github.sha }}
          ghcr.io/${{ github.repository }}:edge
        cache-from: type=local,src=/tmp/.buildx-cache
        cache-to: type=local,dest=/tmp/.buildx-cache

  docs:
    name: docs
    runs-on: ubuntu-latest
    steps:
    -
      name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: true
    -
      name: Set up environment
      run: |
        make init
    -
      name: Publish Site
      uses: chabad360/hugo-gh-pages@master
      with:
        githubToken: ${{ secrets.GITHUB_TOKEN }}
        siteDir: /github/workspace/site
